/* Local interaction prototype. No weather, advertising, analytics or location APIs. */
'use strict';
const D = window.WeatherDemo;
const KEY = 'dayward-prototype-v1';
const defaults = { page: 'weather', place: 'brighton', day: 3, activity: 'outdoors', duration: 2, wind: 20, unit: 'C', theme: 'light', grant: null, trialUsed: false, plans: [], map: false, week: 1, offline: false, noFill: false, noWeekly: false, changed: false };
let stored = {};
try { stored = JSON.parse(localStorage.getItem(KEY) || '{}'); } catch { /* unavailable or corrupt storage */ }
const state = { ...defaults, ...stored };
if (!['weather','plan','weekly','saved'].includes(state.page)) state.page = 'weather';
if (!D.places.some(p => p.id === state.place)) state.place = 'brighton';
if (!Array.isArray(state.plans)) state.plans = [];
state.plans = state.plans.filter(p => p && D.places.some(place => place.id === p.placeId) && typeof p.id === 'string').slice(0, 5);
if (![0,1,2,3,4].includes(state.day)) state.day = 3;
if (!['outdoors','cycling','custom'].includes(state.activity)) state.activity = 'outdoors';
if (![2,3].includes(state.duration)) state.duration = 2;
if (![10,15,20,25].includes(state.wind)) state.wind = 20;
if (![0,1,2].includes(state.week)) state.week = 1;
const app = document.getElementById('app');
const dialog = document.getElementById('dialog');
let toastTimer, adTimer, pendingAction = 'plan', modalOpener;
let storageAvailable = true;
const paths = {
  sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',
  cloud:'<path d="M7 18a5 5 0 1 1 1.2-9.9A6 6 0 0 1 20 10a4 4 0 0 1-1 8Z"/>',
  partly:'<path d="M10 4V2M4.5 6 3 4.5M4 11H2m3.5 5L4 17.5"/><path d="M8 13a4 4 0 1 1 7-4"/><path d="M11 19a3.5 3.5 0 1 1 1-6.8A4.5 4.5 0 0 1 21 14a2.5 2.5 0 0 1-1 5Z"/>',
  pin:'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
  plan:'<rect x="4" y="5" width="16" height="16" rx="3"/><path d="M8 3v4m8-4v4M4 11h16m-12 5 2 2 5-5"/>',
  bookmark:'<path d="M6 4a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v17l-6-4-6 4Z"/>',
  arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',
  chevron:'<path d="m8 10 4 4 4-4"/>',
  search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
  settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3" fill="currentColor"/><circle cx="15" cy="17" r="3" fill="currentColor"/>',
  wind:'<path d="M3 8h12a3 3 0 1 0-3-3M2 12h17a3 3 0 1 1-3 3M4 16h5a3 3 0 1 1-3 3"/>',
  drop:'<path d="M12 2s7 8 7 13a7 7 0 0 1-14 0c0-5 7-13 7-13Z"/>',
  check:'<path d="m5 12 4 4L19 6"/>',
  info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10h.01"/>',
  lock:'<rect x="5" y="10" width="14" height="11" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 4v3"/>',
  unlock:'<rect x="5" y="10" width="14" height="11" rx="3"/><path d="M8 10V7a4 4 0 0 1 7-2m-3 9v3"/>',
  close:'<path d="m6 6 12 12M6 18 18 6"/>',
  map:'<path d="m3 5 6-2 6 3 6-2v16l-6 2-6-3-6 2Zm6-2v16m6-13v16"/>',
  list:'<path d="M9 5h12M9 12h12M9 19h12M3 5h1M3 12h1M3 19h1"/>',
  clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
  trend:'<path d="m3 17 6-6 4 3 8-10m-6 0h6v6"/>',
  leaf:'<path d="M4 20c0-11 9-15 16-16 0 10-3 16-11 16-3 0-5-2-5-5m1 4L16 8"/>',
  play:'<path d="m9 5 11 7-11 7Z"/>',
  bell:'<path d="M5 16v-5a7 7 0 0 1 14 0v5l2 2H3Zm4 5h6"/>',
};
const icon = (name, cls='') => `<svg class="icon ${cls}" viewBox="0 0 24 24" aria-hidden="true">${paths[name] || paths.sun}</svg>`;
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const temp = n => `${state.unit === 'F' ? Math.round(n*9/5+32) : Math.round(n)}°`;
const dayNames = ['Wed','Thu','Fri','Sat','Sun'];
const dayNumbers = ['30','01','02','03','04'];
const dayLabel = d => `${dayNames[d]}, ${dayNumbers[d]} ${d === 0 ? 'September' : 'October'}`;
const active = () => D.hasAccess(state.grant);
const current = () => D.places.find(p=>p.id===state.place);
const result = (id=state.place) => D.scenario(id,state.day,state.activity,state.duration,state.changed,state.wind);
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageAvailable=false;}}
function toast(message){clearTimeout(toastTimer);const el=document.getElementById('toast');el.textContent=message;el.classList.add('visible');toastTimer=setTimeout(()=>el.classList.remove('visible'),3800);}
function nav(page){state.page=page;persist();render();document.getElementById('main').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
function navItems(mobile=false){return [['weather','partly','Weather'],['plan','plan','Plan'],['saved','bookmark','Saved']].map(([page,ico,label])=>`<button data-action="nav" data-page="${page}" class="${state.page===page || (page==='plan'&&state.page==='weekly')?'active':''}" ${state.page===page?'aria-current="page"':''}>${icon(ico)}<span>${label}</span>${!mobile&&page==='saved'&&state.plans.length?`<span class="count">${state.plans.length}</span>`:''}</button>`).join('');}
function render(){
  document.body.classList.toggle('dark',state.theme==='dark');
  const accessLabel = active()?'Planning unlocked':'Free weather, always';
  app.innerHTML=`<aside class="sidebar"><div class="brand"><img src="./mark.svg" alt=""><span>dayward</span></div><p class="brand-tag">Weather for your plans.</p><nav class="nav" aria-label="Main navigation">${navItems()}</nav><div class="side-label">Your places</div>${D.places.map(p=>`<button class="side-place ${state.place===p.id?'selected':''}" data-action="place" data-id="${p.id}"><span>${state.place===p.id?'<span class="dot"></span>':''}${p.name}</span><span>${temp(p.temp)}</span></button>`).join('')}<div class="side-bottom"><div class="access-box">${icon(active()?'unlock':'leaf')}<h3>${accessLabel}</h3><p>${active()?`Access until ${new Date(state.grant.until).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}. Saved plans stay yours.`:'A little more clarity for your next day outside. No subscription.'}</p><button class="text-button" data-action="${active()?'access-info':'unlock'}">${active()?'View access':'Explore planning'} ${icon('arrow')}</button></div><button class="settings-link" data-action="settings">${icon('settings')} Settings & preview</button></div></aside>
  <div class="workspace"><header class="topbar"><div class="brand mobile-brand"><img src="./mark.svg" alt=""><span>dayward</span></div><button class="search-button" data-action="search">${icon('search')} Search a place <kbd>⌘ K</kbd></button><div class="top-actions"><span class="demo-label">INTERACTIVE DEMO</span><button class="unit-button" data-action="unit" aria-label="Switch temperature unit">°${state.unit}</button><button class="icon-button" data-action="settings" aria-label="Settings and preview controls">${icon('settings')}</button><div class="avatar" aria-hidden="true">DW</div></div></header><main id="main" class="main page-enter" tabindex="-1">${state.offline?'<div class="offline-banner">Offline demo · Showing saved example weather. New comparisons are paused.</div>':''}${!storageAvailable?'<div class="offline-banner">Browser storage is unavailable. Changes will last for this tab only.</div>':''}${state.page==='weather'?weatherPage():state.page==='plan'?planPage():state.page==='weekly'?weeklyPage():savedPage()}<footer class="page-footer"><span>Prototype · All weather is fictional · Scenario: 30 Sep–1 Nov 2026</span><button data-action="sources">Data & prototype notes</button></footer></main></div><nav class="mobile-nav" aria-label="Mobile navigation">${navItems(true)}</nav>`;
}
function heading(kicker,title,subtitle,extra=''){return `<div class="page-heading"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${subtitle}</p></div>${extra}</div>`;}
function status(r){return `<span class="status ${r.kind}">${r.label}</span>`;}
function weatherPage(){const p=current(),r=result();return `${heading('A little planning. A better day outside.','Find your window.','Good weather is even better with a plan.',`<div class="date-label">${icon('plan')}${dayLabel(state.day)} · example</div>`)}
  <div class="hero-grid"><section class="weather-hero" aria-label="Example weather"><div class="hero-content"><div class="hero-location"><button class="location-button" data-action="search">${icon('pin')}${p.name}, UK ${icon('chevron')}</button><span class="weather-status">Example forecast</span></div><div class="temperature">${temp(p.temp).replace('°','')}<sup>°</sup></div><p class="hero-description">${state.day===4?'A rainy day. Keep plans flexible.':p.desc}</p><p class="hero-high">High ${temp(p.temp+1)} &nbsp; Low ${temp(p.low)} &nbsp; · &nbsp; ${dayLabel(state.day)}</p></div><div class="hero-footer"><span class="row">${icon('wind')}${p.wind + (state.changed && p.id === 'brighton' ? 12 : 0)} km/h</span><span class="row">${icon('drop')}${state.day===4?75:p.rain}% rain</span><span class="row">${icon('sun')}UV 3</span></div></section>
  <section class="opportunity"><div class="row between"><span class="eyebrow">Your outdoor window</span>${icon('leaf')}</div><div class="window">${r.kind==='unknown'||r.kind==='poor'?'Keep plans flexible':r.window}</div>${status(r)}<p>${r.reason}</p><div class="opportunity-actions"><button class="green-button" data-action="save-current">${icon('bookmark')} Save plan</button><button class="text-button" data-action="why">Why this window ${icon('arrow')}</button></div></section></div>
  <div class="section-row"><h2>Your day, at a glance</h2><div class="day-strip" aria-label="Forecast day">${dayNames.map((name,i)=>`<button class="day-button ${state.day===i?'active':''}" data-action="day" data-day="${i}" aria-pressed="${state.day===i}">${name.toUpperCase()}<strong>${dayNumbers[i]}</strong></button>`).join('')}</div></div>
  <div class="forecast-grid"><section class="card"><div class="card-heading"><h2>Hourly forecast</h2><small>Local time · example</small></div>${hourlyChart(p)}<div class="chart-legend"><span><i class="line-key"></i>Temperature</span><span>Rain probability from one example source</span></div><details><summary>View accessible hourly table</summary>${hourlyTable(p)}</details></section><section class="card"><div class="card-heading"><h2>A forecast with context</h2>${icon('info')}</div><p class="muted small">Wind gusts · selected window</p><div class="model-list">${r.models.map(m=>`<div class="model-row"><span>${m.name}</span><div class="model-bar"><span style="width:${Math.min(100,(m.hours[0].gust||0)*2)}%"></span></div><b>${m.hours[0].gust===null?'—':m.hours[0].gust+' km/h'}</b></div>`).join('')}</div><div class="model-note">${r.kind==='unknown'?'Missing data stays unknown. It is never treated as calm weather.':r.kind==='mixed'?'Different models, different answers. Agreement is not a guarantee.':'Model agreement is useful context, not a promise of accuracy.'}</div><button class="text-button" data-action="why">Understand the forecast ${icon('arrow')}</button></section></div>
  <div class="section-row"><h2>A little further ahead</h2><span class="muted small">Make space for your next adventure</span></div><div class="explore-grid"><button class="explore-card" data-action="nav" data-page="plan"><span class="tile-icon">${icon('map')}</span><div><h3>Same day. A different place.</h3><p>Compare three places, side by side.</p></div>${icon('arrow')}</button><button class="explore-card" data-action="nav" data-page="weekly"><span class="tile-icon warm">${icon('trend')}</span><div><h3>See the bigger picture.</h3><p>Explore weekly trends, with uncertainty in view.</p></div>${icon('arrow')}</button></div>`;}
function hourValues(p){return Array.from({length:8},(_,i)=>({hour:`${8+i*2}:00`,temp:p.temp+[-3,-1,1,2,1,-1,-2,-3][i],rain:state.day===4?75:[5,10,15,15,20,15,10,5][i]}));}
function hourlyChart(p){return `<div class="hour-grid">${hourValues(p).map((h,i)=>`<div><div class="hour">${h.hour}</div>${icon(state.day===4?'cloud':i<4?'partly':'cloud','weather-symbol')}<div class="deg">${temp(h.temp)}</div></div>`).join('')}</div><svg class="chart" viewBox="0 0 600 105" preserveAspectRatio="none" role="img" aria-label="Illustrative temperature curve. Exact example values are in the table below."><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#82a2e3" stop-opacity=".25"/><stop offset="1" stop-color="#82a2e3" stop-opacity="0"/></linearGradient></defs><path d="M0 82C50 82 45 60 85 57S130 31 171 29S220 11 257 12S303 31 343 29S390 58 429 57S470 72 514 70S560 83 600 82V105H0Z" fill="url(#area)"/><path d="M0 82C50 82 45 60 85 57S130 31 171 29S220 11 257 12S303 31 343 29S390 58 429 57S470 72 514 70S560 83 600 82" stroke="#7d9fe1" stroke-width="2" fill="none"/><path d="M0 103H600" stroke="#edf0f5"/></svg><div class="hour-grid">${hourValues(p).map(h=>`<div class="rain">${h.rain}%</div>`).join('')}</div>`;}
function hourlyTable(p){return `<table class="details-table"><caption class="small">Fictional hourly values · °${state.unit}</caption><thead><tr><th>Time</th><th>Temperature</th><th>Rain chance</th></tr></thead><tbody>${hourValues(p).map(h=>`<tr><td>${h.hour}</td><td>${temp(h.temp)}</td><td>${h.rain}%</td></tr>`).join('')}</tbody></table>`;}
function controls(){return `<section class="card plan-controls" aria-label="Planning preferences"><label class="field"><span>Date · example days</span><select id="plan-day" data-change="day">${dayNames.map((n,i)=>`<option value="${i}" ${state.day===i?'selected':''}>${dayLabel(i)}</option>`).join('')}</select></label><label class="field"><span>Activity</span><select data-change="activity"><option value="outdoors" ${state.activity==='outdoors'?'selected':''}>Outdoor time</option><option value="cycling" ${state.activity==='cycling'?'selected':''}>Leisure cycling</option><option value="custom" ${state.activity==='custom'?'selected':''}>Custom preferences</option></select></label><label class="field"><span>Time outside</span><select data-change="duration"><option value="2" ${state.duration===2?'selected':''}>2 hours</option><option value="3" ${state.duration===3?'selected':''}>3 hours</option></select></label><button class="secondary" data-action="preferences">${icon('settings')} Preferences</button></section>`;}
function mapView(){return `<section class="map" aria-label="Illustrative location map, not a navigational or weather map"><svg class="map-art" viewBox="0 0 900 340" preserveAspectRatio="none" aria-hidden="true"><path d="M0 240C110 240 180 315 305 285S520 210 650 226S800 270 900 180V340H0Z" fill="#c8dce0"/><path d="M0 240C110 240 180 315 305 285S520 210 650 226S800 270 900 180" fill="none" stroke="#fff" stroke-width="5"/><path d="M0 53C230 160 289-26 444 82S640 36 900 106M0 126C150 42 336 214 510 119S660 188 900 44M0 189C202 229 340 107 472 180S740 144 900 175" stroke="#dae1d0" stroke-width="25" fill="none"/><path d="M80 0 185 100 356 229 520 105 745 205 900 112M370 0 465 107 630 167 795 0" stroke="#fffdf8" stroke-width="5" fill="none"/><path d="M80 0 185 100 356 229 520 105 745 205 900 112" stroke="#d9cba9" stroke-width="1.5" fill="none"/></svg><span class="map-label" style="left:12%;top:21%">SOUTH DOWNS</span>${D.places.map(p=>`<button class="map-pin" style="left:${p.x}%;top:${p.y}%" data-action="place-details" data-id="${p.id}">${icon('pin')} ${p.name} <b>${temp(p.temp)}</b></button>`).join('')}<span class="map-caption">Illustrative geography · fictional point values · not a weather field</span></section>`;}
function planPage(){return `${heading('Make the most of your time','Where will the day take you?','Same date. Same preferences. A clearer choice.',`<button class="secondary" data-action="nav" data-page="weekly">${icon('trend')} Weekly outlook</button>`)}${controls()}<div class="plan-top"><div class="place-chips">${D.places.map(p=>`<span class="place-chip">${icon('pin')}${p.name}</span>`).join('')}</div><div class="segmented" aria-label="Comparison view"><button data-action="view" data-view="list" class="${!state.map?'active':''}" aria-pressed="${!state.map}">${icon('list')} List</button><button data-action="view" data-view="map" class="${state.map?'active':''}" aria-pressed="${state.map}">${icon('map')} Map</button></div></div>${state.map?mapView():''}${active()?`<div class="compare-cards">${D.places.map(compareCard).join('')}</div><div class="callout">${icon('info')}<span>Each place uses the same preferences and local date. These are illustrative model scenarios, not live forecasts. Unknown conditions are never ranked as better weather.</span></div>`:`<div class="compare-cards">${D.places.map(p=>`<section class="card compare-card"><div class="place-visual ${p.id}"><h3>${p.name}</h3><p>${p.tag}</p></div><div class="compare-body"><p>Compare this place with the same date and preferences.</p><button class="text-button" data-action="place" data-id="${p.id}">View free weather ${icon('arrow')}</button></div></section>`).join('')}</div>${unlockPanel('plan')}`}`;}
function compareCard(p){const r=result(p.id);return `<section class="card compare-card"><div class="place-visual ${p.id}">${r.kind==='good'?'<span class="tag">FITS YOUR PREFERENCES</span>':''}<h3>${p.name}</h3><p>${p.tag}</p></div><div class="compare-body">${status(r)}<div class="compare-window">${r.kind==='unknown'?'No window yet':r.kind==='poor'?'Try another day':r.window}</div><div class="metrics"><div class="metric"><span>${icon('sun')}Temperature</span><b>${temp(p.temp-1)}–${temp(p.temp+1)}</b></div><div class="metric"><span>${icon('drop')}Rain amount</span><b>${state.day===4?'0.4–0.6':'0'} mm/h</b></div><div class="metric"><span>${icon('wind')}Gusts</span><b>${r.kind==='unknown'?'Unavailable':`${Math.min(...r.models.map(m=>m.hours[0].gust))}–${Math.max(...r.models.map(m=>m.hours[0].gust))} km/h`}</b></div></div><p>${r.reason}</p><button class="${r.kind==='good'?'primary':'secondary'} save-button" data-action="save-place" data-id="${p.id}">${icon('bookmark')} ${r.kind==='unknown'||r.kind==='poor'?'Save to follow':'Save this plan'}</button></div></section>`;}
function unlockPanel(target){return `<section class="locked-panel"><div><div class="eyebrow muted">A whole planning session. One simple unlock.</div><h2 style="margin-top:12px">A little more clarity, when you need it.</h2><p>Compare places, fine-tune your preferences and explore available weekly trends. Your everyday weather stays free.</p><div class="locked-preview"><span>${icon('check')}24-hour access</span><span>${icon('check')}No subscription</span><span>${icon('check')}Keep saved plans</span></div></div><button class="primary" data-action="unlock" data-target="${target}">${icon(state.trialUsed?'play':'unlock')}${state.trialUsed?'Unlock planning':'Try planning free'} ${icon('arrow')}</button></section>`;}
function weeklyPage(){return `${heading('Look ahead, with perspective','The bigger picture.','Weekly trends for early planning. Details become clearer closer to the day.',`<button class="secondary" data-action="nav" data-page="plan">${icon('arrow')} Back to planning</button>`)}<section class="outlook-banner"><span class="tile-icon warm">${icon('trend')}</span><div><h2>A trend, not a promise.</h2><p>These views describe a whole week relative to each place’s usual climate. “Drier than usual” does not mean “no rain”. This prototype uses invented trends, not a real seasonal forecast.</p></div></section>${state.noWeekly?`<div class="empty-state"><div class="tile-icon">${icon('cloud')}</div><h2>This outlook is unavailable.</h2><p>There is no supported weekly data in this demo state. We will not ask you to watch an ad for a result we cannot provide.</p><button class="primary" data-action="nav" data-page="plan">Back to short-term planning</button></div>`:active()?`<div class="week-tabs" aria-label="Example outlook week">${['12–18 Oct','19–25 Oct','26 Oct–1 Nov'].map((w,i)=>`<button data-action="week" data-week="${i}" class="${state.week===i?'active':''}" aria-pressed="${state.week===i}">WEEK ${i+3}<strong>${w}</strong></button>`).join('')}</div><section class="card"><div class="card-heading"><h2>${['12–18 October','19–25 October','26 October–1 November'][state.week]}</h2><span class="status mixed">Uncertain outlook</span></div><table class="outlook-table"><thead><tr><th>Place</th><th>Temperature trend</th><th>Rainfall trend</th></tr></thead><tbody>${D.places.map((p,i)=>`<tr><td><strong>${p.name}</strong><small>Whole-week example</small></td><td>${state.week===2?'No clear signal':i===2?'Near usual':'Leaning warmer'}<div class="temperature-range"></div></td><td>${state.week===0?'Near usual':i===1?'Leaning drier':'No clear signal'}<small>Compared with local usual conditions</small></td></tr>`).join('')}</tbody></table><div class="callout">${icon('info')}<span><strong>No clear weather advantage yet.</strong><br>These trends do not establish which place will be warmer or drier in absolute terms. Save an interest and check again closer to your trip.</span></div><button class="text-button" data-action="save-weekly">${icon('bookmark')} Follow this week in ${current().name} ${icon('arrow')}</button></section>`:unlockPanel('weekly')}`;}
function savedPage(){return `${heading('Good plans deserve a second look','Your next days outside.','Saved snapshots stay yours, even after planning access ends.')} ${state.plans.length?`<div class="saved-list">${state.plans.map(p=>`<article class="card saved-card"><div class="saved-thumb" aria-hidden="true"></div><div><div class="eyebrow muted">${p.kind==='weekly'?'Watching the bigger picture':'Your outdoor plan'}</div><h3>${esc(p.placeName)}</h3><div class="saved-meta"><span>${icon('plan')} ${p.kind==='weekly'?esc(p.window):dayLabel(p.day)}</span><span>· ${p.kind==='weekly'?'Weekly trend':esc(p.window)}</span></div><p>${esc(p.status)} · Saved example, ${new Date(p.savedAt).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</p></div><div class="saved-actions"><button class="secondary" data-action="review" data-id="${esc(p.id)}">Review changes ${icon('arrow')}</button><button class="link-danger" data-action="delete-plan" data-id="${esc(p.id)}">Remove plan</button></div></article>`).join('')}</div><div class="callout">${icon('bell')}<span>In this prototype, changes are checked when you open a plan. No real notifications are sent. Turn on “Changed weather” in preview controls to explore the change flow.</span></div>`:`<div class="empty-state"><div class="tile-icon">${icon('bookmark')}</div><h2>A good day starts with a small plan.</h2><p>Save an outdoor window or a place you’re considering. Come back to see what changed.</p><button class="primary" data-action="nav" data-page="weather">Find my window ${icon('arrow')}</button></div>`}`;}
function showDialog(title,body){if(!dialog.open)modalOpener=document.activeElement;dialog.innerHTML=`<div class="dialog-head"><h2 id="dialog-title">${title}</h2><button class="icon-button" data-action="close" aria-label="Close dialog">${icon('close')}</button></div>${body}`;if(!dialog.open)dialog.showModal();}
function closeDialog(){clearInterval(adTimer);dialog.close();if(modalOpener?.isConnected)modalOpener.focus();}
dialog.addEventListener('cancel',()=>clearInterval(adTimer));
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
function showSearch(){showDialog('A change of scenery.',`<p class="dialog-description">Choose an example place in East Sussex. This prototype includes three places; no location permission is needed.</p><input class="search-input" id="place-search" type="search" placeholder="Search Brighton, Lewes…" aria-label="Search example places"><div class="search-results" id="search-results">${searchResults('')}</div>`);document.getElementById('place-search').focus();}
function searchResults(query){const items=D.places.filter(p=>(p.name+' '+p.region).toLowerCase().includes(query.toLowerCase()));return items.length?items.map(p=>`<button class="search-result" data-action="choose-place" data-id="${p.id}">${icon('pin')}<span><strong>${p.name}</strong><small>${p.region}</small></span><b style="margin-left:auto">${temp(p.temp)}</b></button>`).join(''):'<p class="dialog-description">No example matches. Try Brighton, Lewes or Eastbourne.</p>';}
function showWhy(id=state.place){const r=result(id);showDialog('Know the why.',`<p class="dialog-description">${r.place.name} · ${dayLabel(state.day)} · ${r.window}<br>Illustrative model inputs, not actual forecasts.</p>${status(r)}<p class="dialog-description">${r.reason}</p><table class="details-table"><thead><tr><th>Example model</th><th>Mean wind</th><th>Gust</th></tr></thead><tbody>${r.models.map(m=>`<tr><td>${m.name}</td><td>${m.hours[0].wind} km/h</td><td>${m.hours[0].gust===null?'Missing':m.hours[0].gust+' km/h'}</td></tr>`).join('')}</tbody></table><div class="notice">Preference: wind ≤${r.limits.wind} km/h, gust ≤${r.limits.gust} km/h, rain ≤${r.limits.rain} mm/h, temperature ${temp(r.limits.min)}–${temp(r.limits.max)}. These are comfort preferences, not safety limits.</div><p class="dialog-description">Agreement is not an accuracy percentage. Missing values remain unknown, and all complete models must fit before a window is labelled a match.</p><button class="secondary" data-action="sources">Sources & limitations</button>`);}
function showSources(){showDialog('A transparent prototype.',`<p class="dialog-description">Dayward is a working name. Every temperature, model value, map point and weekly trend here is invented for interaction testing.</p><ul class="dialog-list"><li>${icon('check')}No live weather or seasonal API</li><li>${icon('check')}No real ads, tracking or payments</li><li>${icon('check')}No location or notification permission</li><li>${icon('check')}Plans and demo access stay in this browser</li></ul><div class="notice">Model names illustrate a future comparison interface. There are no actual model runs or official warnings in this prototype. It must not be used for weather or safety decisions.</div><p class="dialog-description">Forecast scenario: 30 September 2026. Product concept: free everyday weather, optional rewarded access to planning, and saved plans that remain readable.</p>`);}
function showUnlock(target='plan'){
  pendingAction=target;
  if(state.offline){toast('Offline demo: new planning is paused. Your saved plans remain available.');return;}
  if(target==='weekly'&&state.noWeekly){nav('weekly');return;}
  if(active()){continueAfterUnlock();return;}
  showDialog('Make room for a better plan.',`<div class="reward-symbol" style="margin-top:20px">${icon('unlock')}</div><p class="dialog-description">Unlock the whole planning space for <strong>24 hours</strong>. One session, as many comparisons as you need within the demo.</p><ul class="dialog-list"><li>${icon('check')}Compare up to three places</li><li>${icon('check')}Adjust your activity preferences</li>${!state.noWeekly?`<li>${icon('check')}Explore available weekly outlooks</li>`:''}<li>${icon('check')}Keep your saved plans after access ends</li></ul><div class="dialog-actions">${!state.trialUsed?'<button class="primary" data-action="trial">Try planning free for 24 hours</button>':`<button class="primary" data-action="watch-ad">${icon('play')} Watch demo ad · unlock 24 hours</button>`}<button class="secondary" data-action="close">Continue with free weather</button></div><p class="dialog-footnote">Prototype only · No payment, real ad or subscription.<br>${state.trialUsed?'The next screen simulates an ad reward.':'Your first planning session is on us. No ad required.'}</p>`);
}
function continueAfterUnlock(){closeDialog();if(pendingAction==='preferences'){showPreferences();}else nav(pendingAction==='weekly'?'weekly':'plan');}
function grant(reason){state.grant=D.grantAccess(state.grant,reason);state.trialUsed=true;persist();render();continueAfterUnlock();toast(reason==='grace'?'No ad available. Your 24-hour planning access is on us.':'Planning unlocked for 24 hours. Your saved plans stay yours.');}
function showAd(){
  if(state.offline){closeDialog();toast('Offline. No ad started and your draft is safe.');return;}
  if(state.noFill){grant('grace');return;}
  let remaining=5;
  showDialog('Ad reward simulation',`<div class="ad-art">${icon('leaf')}Take a little outside time.</div><p class="dialog-description">This is a 5-second prototype simulation, not an advertisement. Real ad duration would depend on the ad provider.</p><div class="progress-track"><div id="ad-progress" style="width:0%"></div></div><p class="ad-timer" id="ad-timer">Demo finishes in 5 seconds</p><div class="dialog-actions"><button class="secondary" data-action="close">Cancel · keep using free weather</button></div>`);
  clearInterval(adTimer);
  adTimer=setInterval(()=>{remaining--;const timer=document.getElementById('ad-timer');if(!timer){clearInterval(adTimer);return;}timer.textContent=`Demo finishes in ${remaining} seconds`;document.getElementById('ad-progress').style.width=`${(5-remaining)*20}%`;if(remaining<=0){clearInterval(adTimer);grant('ad-demo');}},1000);
}
function showPreferences(){if(state.offline){toast("Offline demo: preference changes are paused.");return;}if(!active()){showUnlock('preferences');return;}showDialog('Your kind of outside.',`<p class="dialog-description">Fine-tune the wind threshold for your example planning session. These are personal preferences, not safe activity limits.</p><label class="field"><span>Maximum average wind</span><select id="custom-wind">${[10,15,20,25].map(n=>`<option value="${n}" ${state.wind===n?'selected':''}>${n} km/h</option>`).join('')}</select></label><div class="notice">Other demo preferences: temperature 10–28°C, rain ≤0.2 mm/h and gusts ≤30 km/h. Full preference editing is part of the future app.</div><div class="dialog-actions"><button class="primary" data-action="apply-preferences">Apply preferences</button></div>`);}
function savePlan(id=state.place,kind='short'){
  if(state.plans.length>=5){toast('Five plans saved. Remove a demo plan before adding another.');return;}
  if(kind==='weekly'&&!active()){showUnlock('weekly');return;}
  const r=result(id);const plan=D.makePlan(r,state.day,state.activity,kind);
  if(kind==='weekly')plan.window=['12–18 October','19–25 October','26 October–1 November'][state.week];
  state.plans.unshift(plan);persist();render();toast(`Saved ${r.place.name}. Review it in Saved — no ad needed.`);
}
function showReview(id){const p=state.plans.find(p=>p.id===id);if(!p)return;const r=D.scenario(p.placeId,p.day,p.activity,p.duration || 2,state.changed,p.wind ?? 20);showDialog('Has your plan changed?',`<p class="dialog-description">${esc(p.placeName)} · ${p.kind==='weekly'?esc(p.window):dayLabel(p.day)}<br>Your saved example stays readable without planning access.</p><div class="difference"><div><small>SAVED SNAPSHOT</small><strong>${esc(p.status)}</strong><p class="small muted">${esc(p.reason)}</p></div><div><small>LATEST EXAMPLE</small><strong>${p.kind==='weekly'?'Still too early to call':r.label}</strong><p class="small muted">${p.kind==='weekly'?'A whole-week trend cannot tell us the weather on one particular day.':r.reason}</p></div></div><div class="notice">${state.offline?'Offline example: this is cached scenario data, not a fresh update.':p.kind==='weekly'?'There is no clear advantage yet. Keep this week on your shortlist.':r.kind===p.baseline?'No change in this demo scenario. You can keep your plan under review.':'The wind scenario has changed since you saved. Reconsider the time or place before leaving.'}</div><div class="dialog-actions"><button class="primary" data-action="review-weather" data-id="${p.placeId}" data-day="${p.day}">View free weather ${icon('arrow')}</button></div><p class="dialog-footnote">No real background forecast checks or notifications are running.</p>`);}
function showSettings(){showDialog('Settings & preview',`<p class="dialog-description">Prototype controls / 原型演示设置<br>All changes stay in this browser. Use these scenarios to explore the complete flow.</p><label class="control-row"><span>Dark appearance<small>Preview the alternate theme</small></span><input type="checkbox" data-setting="theme" ${state.theme==='dark'?'checked':''}></label><label class="control-row"><span>Offline mode<small>Read cached examples; pause new comparisons</small></span><input type="checkbox" data-setting="offline" ${state.offline?'checked':''}></label><label class="control-row"><span>No ad available<small>Demonstrate complimentary access</small></span><input type="checkbox" data-setting="noFill" ${state.noFill?'checked':''}></label><label class="control-row"><span>Weekly data unavailable<small>No ad offered for unsupported trends</small></span><input type="checkbox" data-setting="noWeekly" ${state.noWeekly?'checked':''}></label><label class="control-row"><span>Changed weather<small>Stronger wind in Brighton for saved-plan review</small></span><input type="checkbox" data-setting="changed" ${state.changed?'checked':''}></label><div class="control-row"><span>Access scenario<small>${active()?'Active 24-hour access':state.trialUsed?'Returning visitor · locked':'First visit · trial available'}</small></span></div><div class="dialog-actions"><button class="secondary" data-action="scenario" data-scenario="returning">Demo returning visitor · show ad unlock</button><button class="secondary" data-action="scenario" data-scenario="first">Demo first visit · free trial</button><button class="secondary" data-action="scenario" data-scenario="expire">Expire access · keep saved plans</button><button class="primary" data-action="close">Done</button></div><p class="dialog-footnote">These controls are for review, not part of the proposed customer interface. No real ads, location, payment or notification services are connected.</p>`);}
document.addEventListener('click',e=>{
  const b=e.target.closest('[data-action]');if(!b)return;
  const action=b.dataset.action;
  switch(action){
    case 'nav':nav(b.dataset.page);break;
    case 'search':showSearch();break;
    case 'place':state.place=b.dataset.id;state.activity='outdoors';nav('weather');break;
    case 'choose-place':state.place=b.dataset.id;state.activity='outdoors';closeDialog();nav('weather');break;
    case 'day':state.day=Number(b.dataset.day);persist();render();break;
    case 'unit':state.unit=state.unit==='C'?'F':'C';persist();render();break;
    case 'why':showWhy();break;
    case 'place-details':showWhy(b.dataset.id);break;
    case 'sources':showSources();break;
    case 'save-current':savePlan();break;
    case 'save-place':if(active())savePlan(b.dataset.id);else showUnlock();break;
    case 'save-weekly':savePlan(state.place,'weekly');break;
    case 'unlock':showUnlock(b.dataset.target||'plan');break;
    case 'access-info':showDialog('Your planning access',`<p class="dialog-description">${active()?`Your demo access is active until ${new Date(state.grant.until).toLocaleString()}.`:'Your planning access has ended.'} Saved snapshots and free weather remain available.</p><div class="dialog-actions"><button class="primary" data-action="access-plan">Explore planning</button></div>`);break;
    case 'access-plan':closeDialog();nav('plan');break;
    case 'trial':grant('trial');break;
    case 'watch-ad':showAd();break;
    case 'close':closeDialog();break;
    case 'view':state.map=b.dataset.view==='map';persist();render();break;
    case 'week':state.week=Number(b.dataset.week);persist();render();break;
    case 'preferences':showPreferences();break;
    case 'apply-preferences':state.wind=Number(document.getElementById('custom-wind').value);state.activity='custom';closeDialog();nav('plan');toast('Preferences updated. The comparison now uses your wind limit.');break;
    case 'review':showReview(b.dataset.id);break;
    case 'review-weather':state.place=b.dataset.id;state.day=Number(b.dataset.day);closeDialog();nav('weather');break;
    case 'delete-plan':state.plans=state.plans.filter(p=>p.id!==b.dataset.id);persist();render();toast('Demo plan removed from this browser.');break;
    case 'settings':showSettings();break;
    case 'scenario':state.trialUsed=b.dataset.scenario!=='first';state.grant=null;persist();render();showSettings();toast('Access scenario changed. Your saved plans are unchanged.');break;
  }
});
document.addEventListener('input',e=>{if(e.target.id==='place-search')document.getElementById('search-results').innerHTML=searchResults(e.target.value);});
document.addEventListener('change',e=>{
  const el=e.target;
  if(el.dataset.setting){const key=el.dataset.setting;state[key]=key==='theme'?(el.checked?'dark':'light'):el.checked;persist();render();return;}
  if(el.dataset.change){if(state.offline){render();toast("Offline demo: reconnect before changing a comparison.");return;}const key=el.dataset.change;if(key==='activity'&&el.value==='custom'&&!active()){el.value=state.activity;showUnlock('preferences');return;}state[key]=key==='activity'?el.value:Number(el.value);persist();render();if(key==='activity'&&state.activity==='custom')showPreferences();}
});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();showSearch();}});
window.addEventListener('focus',()=>{if(!dialog.open)render();});
render();
